apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "restic-backup.fullname" . }}-env-restic
  {{- with .Release.Namespace }}
  namespace: {{ toYaml . }}
  {{- end }}
  labels:
    {{- include "restic-backup.labels" . | nindent 4 }}
data:
  {{- if .Values.restic.cache.enabled }}
  RESTIC_CACHE_DIR: {{ .Values.restic.cache.path | quote }}
  {{- end }}
  RESTIC_RETENTION_HOURLY: {{ .Values.restic.retention.RESTIC_RETENTION_HOURLY | quote }}
  RESTIC_RETENTION_DAILY: {{ .Values.restic.retention.RESTIC_RETENTION_DAILY | quote }}
  RESTIC_RETENTION_WEEKLY: {{ .Values.restic.retention.RESTIC_RETENTION_WEEKLY | quote }}
  RESTIC_RETENTION_MONTHLY: {{ .Values.restic.retention.RESTIC_RETENTION_MONTHLY | quote }}
