{{- if .Values.consul.auth.CONSUL_HTTP_TOKEN }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restic-backup.fullname" . }}-token
  {{- with .Release.Namespace }}
  namespace: {{ toYaml . }}
  {{- end }}
  labels:
    {{- include "restic-backup.labels" . | nindent 4 }}
type: Opaque
data:
  CONSUL_HTTP_TOKEN: {{ .Values.consul.auth.CONSUL_HTTP_TOKEN | b64enc }}
{{- end }}
