apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restic-backup.fullname" . }}-restic
  {{- with .Release.Namespace }}
  namespace: {{ toYaml . }}
  {{- end }}
  labels:
    {{- include "restic-backup.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.restic.repositories.pvc.enabled }}
# pvc
{{ tpl (.Files.Get "conf/pvc.conf") . | indent 2 }}
{{- end }}

{{- if .Values.restic.repositories.s3.enabled }}
# S3
{{ tpl (.Files.Get "conf/s3.conf") . | indent 2 }}
{{- end }}

{{- if .Values.restic.repositories.openstack_v2.enabled }}
# OpenStack keystone v2
{{ tpl (.Files.Get "conf/openstack_v2.conf") . | indent 2 }}
{{- end }}

{{- if .Values.restic.repositories.openstack_v3.enabled }}
# OpenStack keystone v3
{{ tpl (.Files.Get "conf/openstack_v3.conf") . | indent 2 }}
{{- end }}

{{- if .Values.restic.repositories.openstack_application_id.enabled }}
# OpenStack keystone v3 application credential authentication (application credential id)
{{ tpl (.Files.Get "conf/openstack_application_id.conf") . | indent 2 }}
{{- end }}
