# Default values for restic-backup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

cronjob:
  schedule: 0 0 * * *
  backoffLimit: 5
  restartPolicy: "OnFailure"

restic:
  repository: "docker.io/restic/restic"
  tag: "0.12.1"
  pullPolicy: IfNotPresent
  cache:
    enabled: false
    path: "/cache"
    size: 4Gi
    storageClass: ""
    accessModes:
    - ReadWriteOnce

  repositories:
    pvc:
      enabled: true
      RESTIC_REPOSITORY: "/backup"
      RESTIC_PASSWORD: "example"
      size: 20Gi
      storageClass: ""
      accessModes:
      - ReadWriteOnce
    s3:
      enabled: false
      RESTIC_REPOSITORY: "s3:http://example:9000/restic"
      RESTIC_PASSWORD: ""
      AWS_ACCESS_KEY_ID: "<YOUR-S3-ACCESS-KEY-ID>"
      AWS_SECRET_ACCESS_KEY: "<YOUR-S3-SECRET-ACCESS-KEY>"
    openstack_v2:
      enabled: false
      OS_AUTH_URL: ""
      OS_REGION_NAME: ""
      OS_USERNAME: ""
      OS_PASSWORD: ""
      OS_TENANT_ID: ""
      OS_TENANT_NAME: ""
    openstack_v3:
      enabled: false
      OS_AUTH_URL: ""
      OS_REGION_NAME: ""
      OS_USERNAME: ""
      OS_USER_ID: ""
      OS_PASSWORD: ""
      OS_USER_DOMAIN_NAME: ""
      OS_USER_DOMAIN_ID: ""
      OS_PROJECT_NAME: ""
      OS_PROJECT_DOMAIN_NAME: ""
      OS_PROJECT_DOMAIN_ID: ""
      OS_TRUST_ID: ""
    openstack_application_id:
      enabled: false
      OS_AUTH_URL: ""
      OS_APPLICATION_CREDENTIAL_ID: ""
      OS_APPLICATION_CREDENTIAL_SECRET: ""

  retention:
    RESTIC_RETENTION_HOURLY: "24"
    RESTIC_RETENTION_DAILY: "7"
    RESTIC_RETENTION_WEEKLY: "4"
    RESTIC_RETENTION_MONTHLY: "6"

consul:
  enabled: true
  repository: "docker.io/consul"
  tag: "1.10.2"
  pullPolicy: IfNotPresent
  env:
    CONSUL_HTTP_SSL: "false"
    CONSUL_HTTP_ADDR: "consul.consul.svc:8500"
    CONSUL_DATACENTER: ""
  extraEnv: {}
  auth:
    CONSUL_HTTP_TOKEN: ""
    secretKeyRef: {}

customInitContainer: {}
# - name: example
#   image: "example:latest"

podAnnotations: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
