apiVersion: v1
kind: Secret
metadata:
  name: {{ include "librenms.fullname" . }}-config
  labels:
    {{- include "librenms.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.secretEnv }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
