{{- if gt (len .Values.cronJobs) 0 }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "librenms.fullname" . }}-cron
  labels:
    {{- include "librenms.labels" . | nindent 4 }}
data:
  librenms: |
{{- range $item := .Values.cronJobs }}
    {{ $item }}
{{- end }}
{{- end }}
