apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "librenms.fullname" . }}
  labels:
    {{- include "librenms.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "librenms.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "librenms.fullname" . }}
  replicas: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "librenms.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "librenms.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: librenms
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            {{- if gt (len .Values.cronJobs) 0 }}
            - name: cron
              mountPath: /etc/cron.d
              subPath: librenms
            {{- end }}
          env:
            {{- include "librenms.env" . | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "librenms.fullname" . }}-config
        - name: dispatcher
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - name: data
              mountPath: /data
          envFrom:
            - secretRef:
                name: {{ include "librenms.fullname" . }}-config
          env:
            {{- include "librenms.env" . | nindent 12 }}
            - name: DISPATCHER_NODE_ID
              value: dispatcher1
            - name: SIDECAR_DISPATCHER
              value: "1"
        - name: syslogng
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - name: data
              mountPath: /data
          envFrom:
            - secretRef:
                name: {{ include "librenms.fullname" . }}-config
          env:
            {{- include "librenms.env" . | nindent 12 }}
            - name: SIDECAR_SYSLOGNG
              value: "1"
        - name: snmptrapd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - name: data
              mountPath: /data
          envFrom:
            - secretRef:
                name: {{ include "librenms.fullname" . }}-config
          env:
            {{- include "librenms.env" . | nindent 12 }}
            - name: SIDECAR_SNMPTRAPD
              value: "1"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if gt (len .Values.cronJobs) 0 }}
      volumes:
        - name: cron
          configMap:
            name: {{ include "librenms.fullname" . }}-cron
            items:
              - key: librenms
                path: librenms
            defaultMode: 644
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName }}
        {{- end }}
        {{- with .Values.persistence.accessModes }}
        accessModes:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
