{{- if .Values.worker.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netbox.fullname" . }}-worker
  labels:
    {{- include "netbox.labels" . | nindent 4 }}
spec:
{{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "netbox.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  {{ if .Values.worker.updateStrategy -}}
  strategy:
    {{- toYaml .Values.worker.updateStrategy | nindent 4 }}
  {{ end -}}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if (not .Values.existingSecret) }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.worker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "netbox.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "netbox.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-worker
          securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - /opt/netbox/venv/bin/python
            - /opt/netbox/netbox/manage.py
            - rqworker
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SKIP_STARTUP_SCRIPTS
              value: 'True'
            {{- with .Values.extraEnvs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/netbox/config/configuration.py
              subPath: configuration.py
              readOnly: true
            - name: config
              mountPath: /run/config/netbox
              readOnly: true
            - name: secrets
              mountPath: /run/secrets/netbox
              readOnly: true
            - name: netbox-tmp
              mountPath: /tmp
            - name: media
              mountPath: /opt/netbox/netbox/media
              subPath: {{ .Values.persistence.subPath | default "" | quote }}
            {{- if .Values.reportsPersistence.enabled }}
            - name: reports
              mountPath: /opt/netbox/netbox/reports
              subPath: {{ .Values.reportsPersistence.subPath | default "" | quote }}
            {{- end }}
            {{- if or .Values.postgresql.enabled .Values.externalDatabase.existingSecretName }}
            - name: db-secret
              mountPath: /run/secrets/database
              readOnly: true
            {{- end }}
            {{- if .Values.redis.enabled }}
            - name: redis-secret
              mountPath: /run/secrets/redis
              readOnly: true
            {{- else }}
            {{- if .Values.tasksRedis.existingSecretName }}
            - name: redis-tasks-secret
              mountPath: /run/secrets/redis_tasks
              readOnly: true
            {{- end }}
            {{- if .Values.cachingRedis.existingSecretName }}
            - name: redis-caching-secret
              mountPath: /run/secrets/redis_caching
              readOnly: true
            {{- end }}
            {{- end }}
            {{- with .Values.worker.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.worker.resources }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          {{- end }}
        {{- with .Values.worker.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.worker.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "netbox.fullname" . }}
        - name: secrets
          secret:
            {{- if .Values.existingSecret }}
            secretName: {{ .Values.existingSecret | quote }}
            {{- else }}
            secretName: {{ include "netbox.fullname" . }}
            {{- end }}
        - name: netbox-tmp
          emptyDir:
            medium: Memory
        - name: media
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-media" (include "netbox.fullname" .)) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.reportsPersistence.enabled }}
        - name: reports
          persistentVolumeClaim:
            claimName: {{ .Values.reportsPersistence.existingClaim | default (printf "%s-reports" (include "netbox.fullname" .)) }}
        {{- end }}
        {{- if or .Values.postgresql.enabled .Values.externalDatabase.existingSecretName }}
        - name: db-secret
          secret:
            {{- if .Values.postgresql.enabled }}
            secretName: {{ include "netbox.postgresql.fullname" . | quote }}
            {{- else }}
            secretName: {{ .Values.externalDatabase.existingSecretName | quote }}
            {{- end }}
        {{- end }}
        {{- if .Values.redis.enabled }}
        - name: redis-secret
          secret:
            secretName: {{ include "netbox.redis.fullname" . | quote }}
        {{- else }}
        {{- if .Values.tasksRedis.existingSecretName }}
        - name: redis-tasks-secret
          secret:
            secretName: {{ .Values.tasksRedis.existingSecretName | quote }}
        {{- end }}
        {{- if .Values.cachingRedis.existingSecretName }}
        - name: redis-caching-secret
          secret:
            secretName: {{ .Values.cachingRedis.existingSecretName | quote }}
        {{- end }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
